import json
import logging
from typing import List
from app.models.toggl import TogglTimeEntry
from app.models.activity import ActivityMetric
from app.agents.prompts.metric_generator_prompts import build_metric_generator_prompt
from app.services.openai_service import responses

logger = logging.getLogger(__name__)


def generate_all_metrics(
    user_prompt: str, activity_logs: List[TogglTimeEntry]
) -> List[ActivityMetric]:
    """
    Generate activity metrics from time entries using LLM.

    Takes a user prompt and list of TogglTimeEntry objects, then uses an LLM
    to analyze the entries and generate relevant ActivityMetric objects based on
    the user's request.

    Args:
        user_prompt: User's prompt describing what metrics they want
        activity_logs: List of TogglTimeEntry objects to analyze

    Returns:
        List of ActivityMetric objects generated by the LLM
    """
    logger.info(
        f"Generating metrics from {len(activity_logs)} activity logs with prompt: {user_prompt}"
    )

    response_format = _build_response_format()

    prompt = build_metric_generator_prompt(
        primary_objective=user_prompt,
        activity_logs=activity_logs,
        response_format=response_format,
    )

    logger.info(
        f"Calling OpenAI Responses API to generate metrics with prompt: {prompt}"
    )
    response = responses(
        model="gpt-4.1-nano",
        input_text=prompt,
    )

    output_text = response["output_text"]
    logger.info(f"Received raw response from LLM: {output_text}")
    logger.info(f"Received response from LLM: {len(output_text)} characters")

    metrics = _parse_llm_response(output_text)
    logger.info(f"Metrics: {metrics}")
    logger.info(f"Parsed {len(metrics)} metrics from LLM response")

    return metrics


def _build_response_format() -> str:
    """
    Build response format specification for the LLM.

    Returns:
        String describing the expected JSON response format
    """
    return """Return a JSON array of ActivityMetric objects. Each ActivityMetric should have:
- date: Date in YYYY-MM-DD format
- period: One of "1hr", "1day", "1week"
- unit: One of "int", "mins", "hrs", "days"
- value: Numeric value (float)
- title: String title for the metric

Example format:
[
  {
    "date": "2024-01-15",
    "period": "1day",
    "unit": "mins",
    "value": 120.5,
    "title": "Workout Time"
  }
]"""


def _parse_llm_response(output_text: str) -> List[ActivityMetric]:
    """
    Parse LLM response text into List[ActivityMetric].

    Args:
        output_text: Raw text response from LLM (should contain JSON)

    Returns:
        List of ActivityMetric objects

    Raises:
        ValueError: If the response cannot be parsed or validated
    """
    try:
        # Try to extract JSON from the response (in case there's extra text)
        # Look for JSON array pattern
        start_idx = output_text.find("[")
        end_idx = output_text.rfind("]") + 1

        if start_idx == -1 or end_idx == 0:
            raise ValueError("No JSON array found in LLM response")

        json_str = output_text[start_idx:end_idx]
        data = json.loads(json_str)

        metrics = [ActivityMetric.model_validate(metric) for metric in data]
        return metrics

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse JSON from LLM response: {e}")
        raise ValueError(f"Invalid JSON in LLM response: {e}") from e
    except Exception as e:
        logger.error(f"Failed to parse LLM response: {e}")
        raise ValueError(f"Failed to parse LLM response: {e}") from e
