import logging
from typing import List
from app.models.toggl import TogglTimeEntry
from app.models.activity import ActivityMetric

logger = logging.getLogger(__name__)


def generate_all_metrics(
    user_prompt: str, activity_logs: List[TogglTimeEntry]
) -> List[ActivityMetric]:
    """
    Generate activity metrics from time entries using LLM.

    Takes a user prompt and list of TogglTimeEntry objects, then uses an LLM
    to analyze the entries and generate relevant ActivityMetric objects based on
    the user's request.

    Args:
        user_prompt: User's prompt describing what metrics they want
        activity_logs: List of TogglTimeEntry objects to analyze

    Returns:
        List of ActivityMetric objects generated by the LLM
    """
    logger.info(f"Generating metrics from {len(activity_logs)} activity logs with prompt: {user_prompt}")

    # TODO: Implement LLM call to analyze activity_logs and generate metrics
    # The LLM should:
    # 1. Read through the TogglTimeEntry list
    # 2. Understand the user_prompt
    # 3. Generate appropriate ActivityMetric objects
    # 4. Return List[ActivityMetric]

    raise NotImplementedError("LLM-based metric generation not yet implemented")
